services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile.api
    env_file:
      - .env # Load environment variables from the .env file
    ports:
      - "3333:3333" # Expose the API on port 3333
    networks:
      - sznportal_network
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: ./Dockerfile.web
    ports:
      - "3000:3000" # Expose the web app on port 3000
    networks:
      - sznportal_network
    environment:
      - API_URL=http://api:3333/search 
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro                
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro    
      - ./certbot/conf:/etc/letsencrypt                          
      - ./certbot/www:/var/www/certbot                           
    depends_on:
      - web
    networks:
      - sznportal_network  

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email johngoyason@gmail.com -d petquery.b3ning.com --agree-tos
    # command: renew --webroot -w /var/www/certbot --quiet

networks:
  sznportal_network:
    driver: bridge
