name: Run API Tests on Commit

on:
  push:
    branches:
      - '**' # Runs on all branches on push

jobs:
  api-tests:
    runs-on: ubuntu-latest
    environment: schnauzenportal # Ensures GitHub Actions pulls from the correct environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Set up OpenAI API Key
        run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV

      - name: Run API Tests
        run: npm run api:test
