name: Run Frontend Tests

on:
  push:
    branches:
      - main
      - develop
      - feature/** # Runs on feature branches
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    name: Run Frontend Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18 # Adjust based on your project requirements
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run frontend tests
        run: npm run web:test
